name: Run Postman Tests

on: 
  push:
    branches:
      - main  # Change this to your target branch
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Ensure Node.js version is set to 16 or higher

      - name: Install Newman and Dependencies
        run: |
          npm install -g newman newman-reporter-html

      - name: Run Postman Collection
        run: |
          newman run ./Petstore.postman_collection.json -r html  # Make sure this path is correct

      - name: Upload Report
        uses: actions/upload-artifact@v3
        with:
          name: postman-report
          path: newman/*.html  # This assumes the report is saved in the newman directory